### ISSUE TITLE
Looking for discussion

### ISSUE THREAD

**Issue by fsgdrq** [Prabhat1808/CrimePrediction#1]
Hi,  I am also trying to reproduce their work.

Have you met some problems in the part of region embedding? And it seems that POI data is not used in your version. I would like to know about the accuracy and recall rate of the model as I cannot get a good performance when I tried to reproduce.

Looking forward to discussing about the results with you. Thanks.

**Comment by sunil-sopho** [comment]
@fsgdrq  I am sorry for late answer, Prabhat is busy with his master thesis currently, so you can direct your questions to me @ sunilssaharan@gmail.com.  As you said they didn't seem to use region wise data in their work. For our results check the pdf file in the repo.
